#!/bin/bash

set -o errexit -o nounset -o pipefail


# Config
I3_CONFIG_FILE="${HOME}/.config/i3/config"

# Use global rules.
SHORTCUT_LINES="$(cat ${I3_CONFIG_FILE} \
    | grep bindsym \
    | grep -v -e "^#" \
    | grep -v -e "^\ " \
    | grep -v -e "workspace\ [0-9]" \
    | sed  -e 's/bindsym\ //g' \
    | sed  -e 's/\+/\_\+\_/g' \
    | sed  -e 's|local/dev/public/dotfiles/scripts/durxvt|durxvt|g' \
    | sed  -e 's|scrot.*png|screenshot|g' \
    | sed  -e 's|\"||g' \
    | awk  '{ print $1 " " $2 " " $3 " " $4}' \
    | sed  -e 's/\_/\ /g' \
)"

# Use custom rules.
# FILTERED_LINES="$(echo ${SHORTCUT_LINES} \
# )"

# Formal lines.
#    | column -t
#


echo "${SHORTCUT_LINES}"
# echo "${FILTERED_LINES}"
